server.port=8080
spring.application.name=solin-api

spring.datasource.url=jdbc:h2:file:./data/solin;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jackson.deserialization.fail-on-unknown-properties=false

solin.jwt.secret=solin-clyvo-vet-fiap-2026-chave-jwt-mobile-sprint3
solin.jwt.expiration-ms=604800000
